In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path = '/content/raw_sales.csv'
df = pd.read_csv(path)

In [6]:
#1. 제일 위 5줄 출력
print(df.head())


#2. 제일 아래 5줄 출력
print(df.tail())

              datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4
1  2007-02-27 00:00:00      2906  290000        house         3
2  2007-03-07 00:00:00      2905  328000        house         3
3  2007-03-09 00:00:00      2905  380000        house         4
4  2007-03-21 00:00:00      2906  310000        house         3
                  datesold  postcode   price propertyType  bedrooms
29575  2019-07-25 00:00:00      2900  500000         unit         3
29576  2019-07-25 00:00:00      2612  560000         unit         2
29577  2019-07-26 00:00:00      2912  464950         unit         2
29578  2019-07-26 00:00:00      2601  589000         unit         2
29579  2019-07-26 00:00:00      2612  775000         unit         2

In [10]:
#2. 통계 정보 인쇄
    #1. 일반 정보 인쇄
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64
 2   price         29580 non-null  int64
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64
dtypes: int64(3), object(2)
memory usage: 1.1+ MB

In [11]:
    #2. 통계 정보 인쇄: 열 내 숫자로 된 것만 계산해서 보내줍니당
df.describe()

           postcode         price      bedrooms
count  29580.000000  2.958000e+04  29580.000000
mean    2730.249730  6.097363e+05      3.250169
std      146.717292  2.817079e+05      0.951275
min     2600.000000  5.650000e+04      0.000000
25%     2607.000000  4.400000e+05      3.000000
50%     2615.000000  5.500000e+05      3.000000
75%     2905.000000  7.050000e+05      4.000000
max     2914.000000  8.000000e+06      5.000000

In [12]:
# 데이터 원본을 변경하지 않도록 (안전장치), 카피본 생성

sales = df.copy()

In [17]:
# 날짜데이터 (datasold 열)
sales['datesold']


#원래 날짜 데이터에 .dt하면 날짜만 쏙 빠짐
#현재 데이터는 문자열로 쓰여진듯
type(sales['datesold'][0])          # (sales[[열],의 [0번째 행]])

str

In [31]:
#2007-02-07 00:00:00 (문자열 타입으로 입력된 날짜 데이터 분류하기)

#split 사용

#sales['datesold'][0].split(' ')                  #sales['datesold'][0]. = str.
# 결과는 리스트~: ['2007-02-07', '00:00:00']

#뒤에 내용을 삭제하고 앞의 내용만 datesold에 저장하고 싶음
x = sales['datesold'][0].split(' ')[0]
#x
#결과:'2007-02-07'

x.split('-')
#결과: ['2007', '02', '07']

#x의 0번째~분리
x = x.split('-')
year = x[0]
month = x[1]
day = x[2]


#저장은? 얘도 inplace? no~ 함수로 묶어서 받아야함~

In [ ]:
# 날짜와 시간을 분리. 분리한 결과에서 날짜만 사용.
# 날짜에서도 연,월,일로 나누기.
# 연,월,일로 나누는 반복문 만들기.
#     반복문에서 나오는 결과-> 새로운 리스트에 결과값 모두 받아주기
# 이제 다시 한 데이터 프레임으로 만들기
#     그 전에 체크해야할 건 카피본과 분리해낸 연,월,일 리스트가 서로 길이가 같은지 확인
# 체크 결과 이상 없다면 연,월,일 리스트를 데이터 프레임 형식으로 바꿔주기.
# 같은 데이터 프레임 형식이 되었으니 합치기
#     합칠 때 카피본과 연월일 데이터 프레임이 갖고 있는 데이터가 다르니 행과 열 기준을 잘 설정해서 합치기

In [36]:
#함수 묶기 (지금은 datesold의 0번째 행이니까 전반적인 저장을 위해)
#def  ():
years = []                                                      #for문 밖에서 리스트 정의해야함 왜? for문은 돌아가며 새로운 리스트를 계속 생성함. 1리스트 1 원소 꼴
months = []
days = []


for i in range(len(sales)):
    x = sales['datesold'][i].split(' ')[0]                      #결과:'2007-02-07'

    x.split('-')                                                #결과: ['2007', '02', '07']

    #x의 0번째~분리
    x = x.split('-')
    year = x[0]
    month = x[1]
    day = x[2]                                                # 다음에 뭐가 올까: 지금 이 상태는 처음부터 끝까지 분리해줌. 연,월,일 일자를 각각 리스트로 받아주는 함수가 필요해~ (왜냐면 난 sales에 연,월,일을 세 열로 만들고 싶거든)

    #리스트.추가(for문 결과값)                                      # 위치 진짜 못 보겟네 아오
    years.append(year)
    months.append(month)
    days.append(day)                                                #이제 sales에 넣어야해 가장 중요한건 열 길이가 똑같아야함!!

    #print(year, month, day)                                    # 중요: 프린트를 for문 내에 넣어야 전체로 프린트 해줌. for문 밖에 있으면 덮어쓰기를 반복하는 꼴이다!!

In [42]:
print(years)

len(sales) == len(days)       #이제 sales에 넣어야해 가장 중요한건 열 길이가 똑같은지 확인하는 절차

['2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010',

True

In [49]:
#이제 열을 붙여주자

#리스트 -> 데이터 프레임화
#이중리스트 활용

seperated = pd.DataFrame([years, months, days])
seperated = seperated.T


seperated.columns = ['year', 'month', 'day']
seperated

       year month day
0      2007    02  07
1      2007    02  27
2      2007    03  07
3      2007    03  09
4      2007    03  21
...     ...   ...  ..
29575  2019    07  25
29576  2019    07  25
29577  2019    07  26
29578  2019    07  26
29579  2019    07  26

[29580 rows x 3 columns]

In [52]:
#이제 sales에 seperated 합치기

#pd.concat(): 여러 데이터 프레임을 합칠 수 있음

    #문제 발생: sales 와 sperated는 갖고 있는 데이터가 다르니까 a, n \n n, b 꼴임. (디폴트 axis는 0(행)기준)
    #기준이 필요하다: axis = 0,1

result = pd.concat([sales, seperated], axis = 1)

result

,datesold,postcode,price,propertyType,bedrooms,year,month,day
0,2007-02-07 00:00:00,2607,525000,house,4,2007,02,07
1,2007-02-27 00:00:00,2906,290000,house,3,2007,02,27
2,2007-03-07 00:00:00,2905,328000,house,3,2007,03,07
3,2007-03-09 00:00:00,2905,380000,house,4,2007,03,09
4,2007-03-21 00:00:00,2906,310000,house,3,2007,03,21
...,...,...,...,...,...,...,...,...
29575,2019-07-25 00:00:00,2900,500000,unit,3,2019,07,25
29576,2019-07-25 00:00:00,2612,560000,unit,2,2019,07,25
29577,2019-07-26 00:00:00,2912,464950,unit,2,2019,07,26
29578,2019-07-26 00:00:00,2601,589000,unit,2,2019,07,26
29579,2019-07-26 00:00:00,2612,775000,unit,2,2019,07,26

In [53]:
sales

                  datesold  postcode   price propertyType  bedrooms
0      2007-02-07 00:00:00      2607  525000        house         4
1      2007-02-27 00:00:00      2906  290000        house         3
2      2007-03-07 00:00:00      2905  328000        house         3
3      2007-03-09 00:00:00      2905  380000        house         4
4      2007-03-21 00:00:00      2906  310000        house         3
...                    ...       ...     ...          ...       ...
29575  2019-07-25 00:00:00      2900  500000         unit         3
29576  2019-07-25 00:00:00      2612  560000         unit         2
29577  2019-07-26 00:00:00      2912  464950         unit         2
29578  2019-07-26 00:00:00      2601  589000         unit         2
29579  2019-07-26 00:00:00      2612  775000         unit         2

[29580 rows x 5 columns]

In [55]:
years = []                                                      #for문 밖에서 리스트 정의해야함 왜? for문은 돌아가며 새로운 리스트를 계속 생성함. 1리스트 1 원소 꼴
months = []
days = []


for i in range(len(sales)):
    x = sales['datesold'][i].split(' ')[0]                      #결과:'2007-02-07'

    x.split('-')                                                #결과: ['2007', '02', '07']

    #x의 0번째~분리
    x = x.split('-')
    year = x[0]
    month = x[1]
    day = x[2]                                                # 다음에 뭐가 올까: 지금 이 상태는 datehold를 처음부터 끝까지 분리해줌. 분리된 연,월,일 일자를 각각 리스트로 받아주는 함수가 필요해~
                                                                                                                                     #(왜냐면 난 sales에 연,월,일을 세 열로 추가해서 만들고 싶거든)

    #리스트.추가(for문 결과값)                                      # 위치 진짜 못 보겟네 아오
                                                                            #이제 sales에 넣어야해 가장 중요한건 열 길이가 똑같아야함!!

    print(year, month, day)

years.append(year)                          #이렇게 for에서 나온 결과들을 리스트로 받아주는 명령문이 for문 밖에 있으면 리스트로 묶이지 않음 (설명 요청) for에서 시작한 건 for에서 끝내라
 months.append(month)
days.append(day)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
2008 09 16
2008 09 19
2008 09 29
2008 09 30
2008 10 01
2008 10 03
2008 10 07
2008 10 07
2008 10 08
2008 10 10
2008 10 10
2008 10 14
2008 10 21
2008 10 22
2008 10 22
2008 10 23
2008 10 24
2008 10 24
2008 10 31
2008 11 07
2008 11 10
2008 11 14
2008 11 21
2008 11 21
2008 11 27
2008 12 01
2008 12 04
2008 12 04
2008 12 04
2008 12 15
2008 12 15
2008 12 16
2008 12 22
2008 12 23
2008 12 24
2008 12 24
2009 01 05
2009 01 05
2009 01 06
2009 01 07
2009 01 08
2009 01 12
2009 01 20
2009 01 23
2009 01 27
2009 01 29
2009 01 29
2009 01 30
2009 01 30
2009 02 02
2009 02 03
2009 02 03
2009 02 04
2009 02 04
2009 02 06
2009 02 09
2009 02 09
2009 02 09
2009 02 10
2009 02 10
2009 02 10
2009 02 11
2009 02 11
2009 02 12
2009 02 13
2009 02 13
2009 02 17
2009 02 17
2009 02 20
2009 02 23
2009 02 25
2009 02 26
2009 02 26
2009 02 27
2009 02 28
2009 03 02
2009 03 03
2009 03 05
2009 03 05
2009 03 06
2009 03 06
2009 03 11
2009 03 13
2009 03 17
2009 03 20
2009 03 20
2009 03 23
2009 03 25
2009 03 27
2009 03 30
2009 03 30
2009 03 30
2009 04 01
2009 04 03
2009 04 07
2009 04 16
2009 04 16
2009 04 16
2009 04 17
2009 04 17
2009 04 23
2009 04 23
2009 04 28
2009 04 29
2009 04 30
2009 04 30
2009 05 01
2009 05 01
2009 05 06
2009 05 07
2009 05 08
2009 05 12
2009 05 12
2009 05 14
2009 05 18
2009 05 18
2009 05 20
2009 05 20
2009 05 21
2009 05 25
2009 05 25
2009 05 28
2009 06 02
2009 06 02
2009 06 02
2009 06 02
2009 06 12
2009 06 13
2009 06 17
2009 06 18
2009 06 19
2009 06 22
2009 06 22
2009 06 23
2009 06 24
2009 06 25
2009 06 30
2009 06 30
2009 07 08
2009 07 08
2009 07 13
2009 07 14
2009 07 14
2009 07 15
2009 07 17
2009 07 21
2009 07 21
2009 07 21
2009 07 22
2009 07 22
2009 07 22
2009 07 24
2009 07 27
2009 07 28
2009 08 03
2009 08 03
2009 08 04
2009 08 04
2009 08 06
2009 08 06
2009 08 06
2009 08 10
2009 08 11
2009 08 14
2009 08 17
2009 08 17
2009 08 20
2009 08 28
2009 08 28
2009 08 28
2009 09 03
2009 09 11
2009 09 11
2009 09 15
2009 09 18
2009 09 22
2009 09 23
2009 09 27
2009 09 29
2009 09 29
2009 09 29
2009 09 30
2009 09 30
2009 10 01
2009 10 01
2009 10 08
2009 10 12
2009 10 16
2009 10 19
2009 10 22
2009 10 23
2009 10 23
2009 10 24
2009 10 26
2009 10 29
2009 10 29
2009 10 30
2009 11 04
2009 11 04
2009 11 06
2009 11 09
2009 11 16
2009 11 16
2009 11 20
2009 11 20
2009 11 23
2009 11 27
2009 11 27
2009 11 30
2009 12 07
2009 12 10
2009 12 14
2009 12 15
2009 12 15
2009 12 16
2009 12 17
2009 12 18
2009 12 18
2009 12 19
2009 12 21
2009 12 21
2009 12 22
2009 12 22
2009 12 22
2009 12 23
2009 12 24
2009 12 24
2010 01 11
2010 01 11
2010 01 15
2010 01 18
2010 01 20
2010 01 22
2010 01 29
2010 01 29
2010 02 02
2010 02 02
2010 02 04
2010 02 05
2010 02 09
2010 02 10
2010 02 10
2010 02 17
2010 02 17
2010 02 17
2010 02 18
2010 02 22
2010 02 24
2010 03 01
2010 03 03
2010 03 03
2010 03 03
2010 03 05
2010 03 09
2010 03 09
2010 03 11
2010 03 12
2010 03 15
2010 03 15
2010 03 17
2010 03 17
2010 03 18
2010 03 19
2010 03 19
2010 03 29
2010 03 30
2010 03 30
2010 03 31
2010 04 09
2010 04 12
2010 04 12
2010 04 15
2010 04 16
2010 04 21
2010 04 22
2010 04 27
2010 04 27
2010 05 03
2010 05 03
2010 05 04
2010 05 05
2010 05 06
2010 05 07
2010 05 13
2010 05 13
2010 05 14
2010 05 21
2010 05 21
2010 05 24
2010 05 26
2010 05 27
2010 05 27
2010 05 28
2010 06 02
2010 06 02
2010 06 02
2010 06 03
2010 06 03
2010 06 08
2010 06 15
2010 06 17
2010 06 17
2010 06 23
2010 06 23
2010 06 26
2010 06 28
2010 07 06
2010 07 07
2010 07 08
2010 07 12
2010 07 13
2010 07 15
2010 07 15
2010 07 16
2010 07 19
2010 07 20
2010 07 21
2010 07 23
2010 07 23
2010 07 26
2010 07 28
2010 07 28
2010 07 29
2010 07 30
2010 08 04
2010 08 05
2010 08 09
2010 08 12
2010 08 12
2010 08 13
2010 08 13
2010 08 16
2010 08 17
2010 08 17
2010 08 20
2010 08 23
2010 08 24
2010 08 25
2010 08 26
2010 08 26
2010 08 26
2010 08 27
2010 08 27
2010 08 30
2010 09 01
2010 09 06
2010 09 07
2010 09 10
2010 09 10
2010 09 10
2010 09 13
2010 09 13
2010 09 16
2010 09 16
2010 09 17
2010 09 17
2010 09 17
2010 09 20
2010 09 20
2010 09 22
2010 09 28
2010 09 29
2010 09 29
2010 09 30
2010 10 05
2010 10 06
2010 10 06
2010 10 07
2010 10 11
2010 10 12
2010 10 12
2010 10 13
2010 10 15
2010 10 15
2010 10 16
2010 10 18
2010 10 18
2010 10 19
2010 10 22
2010 10 22
2010 10 25
2010 10 26
2010 10 26
2010 10 28
2010 10 29
2010 10 29
2010 11 02
2010 11 04
2010 11 12
2010 11 18
2010 11 22
2010 11 23
2010 11 23
2010 11 25
2010 11 27
2010 12 03
2010 12 04
2010 12 06
2010 12 08
2010 12 08
2010 12 13
2010 12 13
2010 12 14
2010 12 15
2010 12 20
2010 12 21
2010 12 24
2010 12 30
2011 01 07
2011 01 11
2011 01 12
2011 01 12
2011 01 17
2011 01 17
2011 01 18
2011 01 19
2011 01 19
2011 01 24
2011 01 27
2011 01 29
2011 01 31
2011 02 01
2011 02 03
2011 02 09
2011 02 09
2011 02 09
2011 02 09
2011 02 09
2011 02 11
2011 02 17
2011 02 17
2011 02 17
2011 02 18
2011 02 21
2011 02 21
2011 02 24
2011 02 24
2011 02 28
2011 03 01
2011 03 07
2011 03 07
2011 03 07
2011 03 15
2011 03 17
2011 03 18
2011 03 18
2011 03 21
2011 03 21
2011 03 22
2011 03 24
2011 03 24
2011 03 29
2011 03 31
2011 04 04
2011 04 05
2011 04 09
2011 04 12
2011 04 13
2011 04 16
2011 04 19
2011 04 20
2011 04 20
2011 04 21
2011 04 21
2011 04 28
2011 04 28
2011 04 29
2011 05 02
2011 05 04
2011 05 09
2011 05 10
2011 05 11
2011 05 11
2011 05 12
2011 05 13
2011 05 16
2011 05 17
2011 05 17
2011 05 17
2011 05 18
2011 05 18
2011 05 23
2011 05 24
2011 05 25
2011 05 27
2011 05 31
2011 06 01
2011 06 03
2011 06 09
2011 06 09
2011 06 10
2011 06 20
2011 06 23
2011 07 05
2011 07 12
2011 07 12
2011 07 13
2011 07 13
2011 07 14
2011 07 15
2011 07 15
2011 07 20
2011 07 21
2011 07 22
2011 07 26
2011 08 03
2011 08 04
2011 08 06
2011 08 08
2011 08 10
2011 08 11
2011 08 11
2011 08 11
2011 08 15
2011 08 16
2011 08 18
2011 08 19
2011 08 23
2011 08 23
2011 08 29
2011 08 29
2011 08 30
2011 08 31
2011 08 31
2011 09 02
2011 09 02
2011 09 05
2011 09 06
2011 09 08
2011 09 08
2011 09 09
2011 09 12
2011 09 12
2011 09 12
2011 09 13
2011 09 13
2011 09 15
2011 09 15
2011 09 16
2011 09 19
2011 09 19
2011 09 20
2011 09 21
2011 09 23
2011 09 30
2011 10 04
2011 10 07
2011 10 13
2011 10 14
2011 10 14
2011 10 17
2011 10 17
2011 10 17
2011 10 19
2011 10 19
2011 10 19
2011 10 20
2011 10 21
2011 10 21
2011 10 24
2011 10 25
2011 10 28
2011 10 28
2011 10 28
2011 10 30
2011 11 01
2011 11 02
2011 11 03
2011 11 04
2011 11 04
2011 11 07
2011 11 07
2011 11 07
2011 11 08
2011 11 08
2011 11 08
2011 11 11
2011 11 14
2011 11 14
2011 11 15
2011 11 19
2011 11 22
2011 11 23
2011 11 23
2011 11 23
2011 11 24
2011 12 01
2011 12 05
2011 12 08
2011 12 12
2011 12 14
2011 12 14
2011 12 16
2011 12 17
2011 12 20
2011 12 20
2011 12 20
2011 12 21
2011 12 21
2011 12 22
2011 12 22
2011 12 23
2012 01 03
2012 01 05
2012 01 09
2012 01 11
2012 01 16
2012 01 18
2012 01 20
2012 01 23
2012 01 24
2012 01 25
2012 01 26
2012 01 31
2012 02 03
2012 02 06
2012 02 08
2012 02 10
2012 02 10
2012 02 13
2012 02 13
2012 02 17
2012 02 17
2012 02 17
2012 02 18
2012 02 20
2012 02 20
2012 02 22
2012 02 24
2012 02 27
2012 02 27
2012 02 28
2012 02 29
2012 03 02
2012 03 05
2012 03 07
2012 03 07
2012 03 07
2012 03 07
2012 03 08
2012 03 08
2012 03 13
2012 03 14
2012 03 14
2012 03 16
2012 03 20
2012 03 23
2012 03 23
2012 03 23
2012 03 29
2012 03 30
2012 03 30
2012 03 30
2012 04 02
2012 04 05
2012 04 11
2012 04 12
2012 04 12
2012 04 12
2012 04 14
2012 04 17
2012 04 17
2012 04 19
2012 04 23
2012 04 26
2012 04 26
2012 04 26
2012 04 26
2012 04 27
2012 04 27
2012 05 04
2012 05 04
2012 05 10
2012 05 11
2012 05 16
2012 05 17
2012 05 18
2012 05 18
2012 05 18
2012 05 22
2012 05 22
2012 05 22
2012 05 23
2012 05 23
2012 05 23
2012 05 25
2012 05 30
2012 05 30
2012 05 31
2012 06 01
2012 06 05
2012 06 05
2012 06 05
2012 06 06
2012 06 07
2012 06 07
2012 06 08
2012 06 18
2012 06 19
2012 06 21
2012 06 25
2012 06 29
2012 07 03
2012 07 06
2012 07 06
2012 07 10
2012 07 11
2012 07 11
2012 07 11
2012 07 17
2012 07 20
2012 07 23
2012 07 23
2012 07 23
2012 07 23
2012 07 24
2012 07 26
2012 07 28
2012 07 31
2012 08 01
2012 08 02
2012 08 02
2012 08 02
2012 08 06
2012 08 08
2012 08 08
2012 08 10
2012 08 10
2012 08 10
2012 08 10
2012 08 13
2012 08 15
2012 08 16
2012 08 17
2012 08 17
2012 08 17
2012 08 21
2012 08 21
2012 08 22
2012 08 23
2012 08 25
2012 08 27
2012 08 28
2012 08 30
2012 08 30
2012 09 01
2012 09 03
2012 09 04
2012 09 06
2012 09 06
2012 09 07
2012 09 07
2012 09 10
2012 09 10
2012 09 10
2012 09 10
2012 09 11
2012 09 11
2012 09 12
2012 09 13
2012 09 13
2012 09 14
2012 09 18
2012 09 19
2012 09 19
2012 09 20
2012 09 20
2012 09 20
2012 09 21
2012 09 21
2012 09 24
2012 09 25
2012 09 25
2012 09 26
2012 09 28
2012 10 02
2012 10 03
2012 10 03
2012 10 03
2012 10 04
2012 10 05
2012 10 09
2012 10 10
2012 10 10
2012 10 12
2012 10 12
2012 10 12
2012 10 15
2012 10 15
2012 10 16
2012 10 16
2012 10 16
2012 10 17
2012 10 19
2012 10 22
2012 10 22
2012 10 23
2012 10 24
2012 10 29
2012 10 29
2012 10 29
2012 10 30
2012 10 31
2012 10 31
2012 10 31
2012 11 01
2012 11 02
2012 11 02
2012 11 02
2012 11 03
2012 11 05
2012 11 07
2012 11 08
2012 11 09
2012 11 09
2012 11 10
2012 11 12
2012 11 13
2012 11 16
2012 11 19
2012 11 19
2012 11 20
2012 11 21
2012 11 21
2012 11 23
2012 11 25
2012 11 26
2012 11 27
2012 12 01
2012 12 03
2012 12 03
2012 12 04
2012 12 06
2012 12 06
2012 12 07
2012 12 07
2012 12 07
2012 12 08
2012 12 11
2012 12 11
2012 12 11
2012 12 12
2012 12 13
2012 12 17
2012 12 17
2012 12 18
2012 12 21
2012 12 21
2013 01 07
2013 01 07
2013 01 10
2013 01 10
2013 01 10
2013 01 10
2013 01 11
2013 01 15
2013 01 17
2013 01 18
2013 01 18
2013 01 22
2013 01 22
2013 01 23
2013 01 23
2013 01 24
2013 01 25
2013 01 29
2013 01 29
2013 01 30
2013 01 31
2013 02 01
2013 02 04
2013 02 04
2013 02 05
2013 02 05
2013 02 08
2013 02 08
2013 02 08
2013 02 12
2013 02 12
2013 02 13
2013 02 15
2013 02 15
2013 02 15
2013 02 18
2013 02 19
2013 02 19
2013 02 19
2013 02 20
2013 02 21
2013 02 22
2013 02 27
2013 02 28
2013 02 28
2013 03 01
2013 03 01
2013 03 01
2013 03 04
2013 03 05
2013 03 05
2013 03 07
2013 03 08
2013 03 14
2013 03 14
2013 03 15
2013 03 15
2013 03 15
2013 03 18
2013 03 18
2013 03 19
2013 03 19
2013 03 20
2013 03 22
2013 03 25
2013 03 25
2013 03 25
2013 03 25
2013 03 27
2013 03 28
2013 03 28
2013 04 02
2013 04 03
2013 04 03
2013 04 04
2013 04 05
2013 04 05
2013 04 05
2013 04 05
2013 04 06
2013 04 08
2013 04 08
2013 04 09
2013 04 09
2013 04 09
2013 04 13
2013 04 13
2013 04 15
2013 04 17
2013 04 19
2013 04 19
2013 04 22
2013 04 22
2013 04 23
2013 04 24
2013 04 29
2013 04 29
2013 05 01
2013 05 01
2013 05 02
2013 05 04
2013 05 06
2013 05 06
2013 05 06
2013 05 06
2013 05 09
2013 05 09
2013 05 10
2013 05 13
2013 05 13
2013 05 13
2013 05 14
2013 05 14
2013 05 15
2013 05 17
2013 05 20
2013 05 23
2013 05 27
2013 05 28
2013 05 29
2013 05 30
2013 05 31
2013 06 03
2013 06 03
2013 06 03
2013 06 04
2013 06 04
2013 06 04
2013 06 05
2013 06 07
2013 06 07
2013 06 07
2013 06 07
2013 06 11
2013 06 13
2013 06 14
2013 06 14
2013 06 14
2013 06 17
2013 06 18
2013 06 18
2013 06 19
2013 06 25
2013 06 26
2013 06 27
2013 07 01
2013 07 02
2013 07 03
2013 07 04
2013 07 08
2013 07 09
2013 07 10
2013 07 12
2013 07 15
2013 07 16
2013 07 16
2013 07 18
2013 07 19
2013 07 22
2013 07 23
2013 07 23
2013 07 24
2013 07 24
2013 07 25
2013 07 29
2013 07 30
2013 07 31
2013 07 31
2013 08 01
2013 08 01
2013 08 02
2013 08 06
2013 08 06
2013 08 08
2013 08 08
2013 08 15
2013 08 16
2013 08 19
2013 08 19
2013 08 21
2013 08 21
2013 08 21
2013 08 21
2013 08 21
2013 08 22
2013 08 23
2013 08 23
2013 08 27
2013 08 28
2013 08 28
2013 08 29
2013 08 29
2013 08 29
2013 08 29
2013 08 30
2013 08 30
2013 08 30
2013 09 01
2013 09 02
2013 09 03
2013 09 03
2013 09 03
2013 09 04
2013 09 05
2013 09 10
2013 09 10
2013 09 11
2013 09 11
2013 09 12
2013 09 18
2013 09 18
2013 09 19
2013 09 19
2013 09 20
2013 09 21
2013 09 23
2013 09 25
2013 09 25
2013 09 27
2013 10 03
2013 10 04
2013 10 09
2013 10 09
2013 10 14
2013 10 16
2013 10 18
2013 10 24
2013 10 24
2013 10 25
2013 10 29
2013 10 31
2013 11 04
2013 11 06
2013 11 06
2013 11 07
2013 11 07
2013 11 11
2013 11 14
2013 11 15
2013 11 18
2013 11 19
2013 11 19
2013 11 19
2013 11 19
2013 11 20
2013 11 21
2013 11 21
2013 11 21
2013 11 25
2013 11 27
2013 11 27
2013 11 27
2013 11 28
2013 11 28
2013 11 28
2013 11 28
2013 11 28
2013 11 29
2013 12 03
2013 12 04
2013 12 06
2013 12 09
2013 12 09
2013 12 11
2013 12 11
2013 12 13
2013 12 14
2013 12 16
2013 12 18
2013 12 18
2013 12 19
2013 12 19
2013 12 20
2013 12 20
2013 12 20
2013 12 20
2013 12 24
2013 12 24
2014 01 07
2014 01 13
2014 01 13
2014 01 16
2014 01 17
2014 01 17
2014 01 17
2014 01 20
2014 01 21
2014 01 21
2014 01 28
2014 01 28
2014 01 29
2014 01 30
2014 01 31
2014 01 31
2014 01 31
2014 01 31
2014 02 03
2014 02 03
2014 02 03
2014 02 04
2014 02 04
2014 02 07
2014 02 07
2014 02 07
2014 02 08
2014 02 10
2014 02 11
2014 02 11
2014 02 11
2014 02 12
2014 02 13
2014 02 14
2014 02 17
2014 02 18
2014 02 18
2014 02 18
2014 02 19
2014 02 19
2014 02 19
2014 02 19
2014 02 21
2014 02 22
2014 02 22
2014 02 24
2014 02 25
2014 02 25
2014 02 25
2014 02 26
2014 02 27
2014 02 27
2014 02 28
2014 02 28
2014 03 03
2014 03 04
2014 03 06
2014 03 06
2014 03 06
2014 03 06
2014 03 06
2014 03 07
2014 03 13
2014 03 15
2014 03 17
2014 03 18
2014 03 18
2014 03 18
2014 03 18
2014 03 19
2014 03 19
2014 03 19
2014 03 19
2014 03 20
2014 03 21
2014 03 21
2014 03 21
2014 03 21
2014 03 21
2014 03 22
2014 03 26
2014 03 26
2014 03 27
2014 03 27
2014 03 31
2014 03 31
2014 03 31
2014 03 31
2014 04 02
2014 04 03
2014 04 04
2014 04 04
2014 04 09
2014 04 09
2014 04 10
2014 04 11
2014 04 11
2014 04 14
2014 04 14
2014 04 14
2014 04 16
2014 04 17
2014 04 17
2014 04 22
2014 04 22
2014 04 22
2014 04 22
2014 04 29
2014 04 29
2014 04 29
2014 04 30
2014 04 30
2014 05 01
2014 05 01
2014 05 02
2014 05 05
2014 05 06
2014 05 08
2014 05 09
2014 05 12
2014 05 12
2014 05 12
2014 05 14
2014 05 16
2014 05 16
2014 05 19
2014 05 20
2014 05 20
2014 05 20
2014 05 20
2014 05 24
2014 05 26
2014 05 27
2014 05 31
2014 05 31
2014 06 02
2014 06 02
2014 06 02
2014 06 05
2014 06 06
2014 06 12
2014 06 12
2014 06 12
2014 06 13
2014 06 14
2014 06 16
2014 06 17
2014 06 17
2014 06 19
2014 06 23
2014 06 27
2014 06 30
2014 06 30
2014 07 03
2014 07 03
2014 07 04
2014 07 04
2014 07 05
2014 07 09
2014 07 09
2014 07 09
2014 07 10
2014 07 10
2014 07 10
2014 07 11
2014 07 14
2014 07 14
2014 07 15
2014 07 16
2014 07 16
2014 07 17
2014 07 21
2014 07 21
2014 07 22
2014 07 22
2014 07 24
2014 07 24
2014 07 25
2014 07 28
2014 07 28
2014 07 30
2014 07 31
2014 07 31
2014 08 01
2014 08 01
2014 08 05
2014 08 06
2014 08 06
2014 08 06
2014 08 07
2014 08 08
2014 08 08
2014 08 11
2014 08 11
2014 08 11
2014 08 13
2014 08 13
2014 08 13
2014 08 18
2014 08 19
2014 08 19
2014 08 19
2014 08 20
2014 08 20
2014 08 26
2014 08 26
2014 08 26
2014 08 27
2014 08 27
2014 08 28
2014 08 29
2014 08 29
2014 08 29
2014 09 01
2014 09 03
2014 09 03
2014 09 05
2014 09 05
2014 09 06
2014 09 09
2014 09 09
2014 09 12
2014 09 15
2014 09 15
2014 09 16
2014 09 17
2014 09 17
2014 09 17
2014 09 18
2014 09 20
2014 09 22
2014 09 22
2014 09 25
2014 09 25
2014 09 25
2014 09 26
2014 09 26
2014 09 26
2014 09 30
2014 10 01
2014 10 01
2014 10 01
2014 10 01
2014 10 03
2014 10 07
2014 10 08
2014 10 09
2014 10 09
2014 10 10
2014 10 13
2014 10 14
2014 10 14
2014 10 14
2014 10 15
2014 10 15
2014 10 15
2014 10 15
2014 10 15
2014 10 16
2014 10 17
2014 10 17
2014 10 21
2014 10 21
2014 10 22
2014 10 23
2014 10 24
2014 10 24
2014 10 27
2014 10 27
2014 10 27
2014 10 29
2014 10 29
2014 10 29
2014 10 30
2014 11 01
2014 11 01
2014 11 04
2014 11 05
2014 11 05
2014 11 05
2014 11 06
2014 11 06
2014 11 06
2014 11 07
2014 11 07
2014 11 10
2014 11 10
2014 11 10
2014 11 10
2014 11 11
2014 11 11
2014 11 11
2014 11 12
2014 11 12
2014 11 13
2014 11 14
2014 11 15
2014 11 17
2014 11 20
2014 11 20
2014 11 20
2014 11 21
2014 11 21
2014 11 22
2014 11 22
2014 11 24
2014 11 24
2014 11 24
2014 11 24
2014 11 24
2014 11 25
2014 11 25
2014 11 28
2014 11 29
2014 12 01
2014 12 01
2014 12 02
2014 12 02
2014 12 03
2014 12 03
2014 12 04
2014 12 04
2014 12 05
2014 12 08
2014 12 08
2014 12 08
2014 12 09
2014 12 09
2014 12 09
2014 12 10
2014 12 10
2014 12 11
2014 12 11
2014 12 12
2014 12 14
2014 12 15
2014 12 15
2014 12 16
2014 12 16
2014 12 16
2014 12 17
2014 12 17
2014 12 17
2014 12 18
2014 12 18
2014 12 18
2014 12 19
2014 12 19
2014 12 22
2014 12 22
2014 12 22
2014 12 22
2014 12 22
2014 12 23
2014 12 23
2014 12 24
2015 01 06
2015 01 08
2015 01 08
2015 01 09
2015 01 12
2015 01 15
2015 01 15
2015 01 20
2015 01 23
2015 01 23
2015 01 28
2015 01 29
2015 01 30
2015 01 30
2015 01 30
2015 01 31
2015 02 02
2015 02 02
2015 02 03
2015 02 03
2015 02 03
2015 02 04
2015 02 04
2015 02 04
2015 02 05
2015 02 05
2015 02 05
2015 02 05
2015 02 06
2015 02 06
2015 02 06
2015 02 07
2015 02 09
2015 02 10
2015 02 10
2015 02 10
2015 02 10
2015 02 11
2015 02 11
2015 02 12
2015 02 12
2015 02 13
2015 02 13
2015 02 16
2015 02 16
2015 02 16
2015 02 16
2015 02 17
2015 02 18
2015 02 18
2015 02 18
2015 02 18
2015 02 18
2015 02 18
2015 02 19
2015 02 19
2015 02 19
2015 02 19
2015 02 19
2015 02 20
2015 02 20
2015 02 20
2015 02 21
2015 02 21
2015 02 23
2015 02 23
2015 02 24
2015 02 24
2015 02 24
2015 02 25
2015 02 25
2015 02 25
2015 02 26
2015 02 26
2015 02 26
2015 02 26
2015 02 27
2015 02 27
2015 02 27
2015 03 03
2015 03 03
2015 03 04
2015 03 04
2015 03 04
2015 03 04
2015 03 05
2015 03 05
2015 03 05
2015 03 05
2015 03 05
2015 03 06
2015 03 06
2015 03 07
2015 03 10
2015 03 10
2015 03 11
2015 03 11
2015 03 12
2015 03 13
2015 03 14
2015 03 15
2015 03 16
2015 03 16
2015 03 17
2015 03 17
2015 03 17
2015 03 17
2015 03 19
2015 03 20
2015 03 20
2015 03 20
2015 03 20
2015 03 23
2015 03 23
2015 03 24
2015 03 24
2015 03 25
2015 03 26
2015 03 26
2015 03 27
2015 03 27
2015 03 27
2015 03 27
2015 03 28
2015 03 30
2015 03 30
2015 03 31
2015 04 02
2015 04 08
2015 04 09
2015 04 09
2015 04 09
2015 04 10
2015 04 10
2015 04 11
2015 04 13
2015 04 14
2015 04 14
2015 04 15
2015 04 16
2015 04 17
2015 04 17
2015 04 17
2015 04 20
2015 04 20
2015 04 20
2015 04 20
2015 04 20
2015 04 21
2015 04 22
2015 04 22
2015 04 22
2015 04 22
2015 04 22
2015 04 23
2015 04 24
2015 04 24
2015 04 24
2015 04 27
2015 04 27
2015 04 28
2015 04 28
2015 04 28
2015 04 28
2015 04 29
2015 04 29
2015 04 29
2015 04 29
2015 04 29
2015 04 30
2015 04 30
2015 05 01
2015 05 04
2015 05 04
2015 05 04
2015 05 05
2015 05 05
2015 05 06
2015 05 07
2015 05 07
2015 05 08
2015 05 08
2015 05 09
2015 05 11
2015 05 11
2015 05 11
2015 05 12
2015 05 12
2015 05 13
2015 05 13
2015 05 13
2015 05 14
2015 05 14
2015 05 15
2015 05 18
2015 05 19
2015 05 19
2015 05 19
2015 05 20
2015 05 20
2015 05 21
2015 05 21
2015 05 21
2015 05 21
2015 05 21
2015 05 21
2015 05 22
2015 05 22
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 25
2015 05 27
2015 05 28
2015 05 28
2015 05 29
2015 06 01
2015 06 01
2015 06 01
2015 06 01
2015 06 02
2015 06 02
2015 06 04
2015 06 04
2015 06 05
2015 06 05
2015 06 05
2015 06 05
2015 06 06
2015 06 09
2015 06 10
2015 06 10
2015 06 11
2015 06 11
2015 06 11
2015 06 15
2015 06 16
2015 06 18
2015 06 19
2015 06 19
2015 06 19
2015 06 22
2015 06 23
2015 06 23
2015 06 23
2015 06 25
2015 06 25
2015 06 25
2015 06 26
2015 06 26
2015 06 26
2015 06 26
2015 06 26
2015 06 26
2015 06 27
2015 06 29
2015 06 30
2015 06 30
2015 06 30
2015 07 01
2015 07 01
2015 07 02
2015 07 02
2015 07 02
2015 07 03
2015 07 03
2015 07 03
2015 07 04
2015 07 06
2015 07 06
2015 07 06
2015 07 06
2015 07 07
2015 07 08
2015 07 08
2015 07 08
2015 07 10
2015 07 10
2015 07 10
2015 07 13
2015 07 13
2015 07 13
2015 07 14
2015 07 16
2015 07 17
2015 07 17
2015 07 17
2015 07 17
2015 07 20
2015 07 22
2015 07 22
2015 07 22
2015 07 23
2015 07 24
2015 07 24
2015 07 24
2015 07 24
2015 07 28
2015 07 28
2015 07 28
2015 07 29
2015 07 29
2015 07 29
2015 07 30
2015 07 30
2015 07 31
2015 07 31
2015 07 31
2015 07 31
2015 08 03
2015 08 04
2015 08 04
2015 08 04
2015 08 05
2015 08 05
2015 08 06
2015 08 06
2015 08 06
2015 08 07
2015 08 10
2015 08 10
2015 08 11
2015 08 12
2015 08 12
2015 08 12
2015 08 13