#머신러닝

- 분류, 회귀, 군집화에 사용 가능한 알고리즘   
- 차원축소에 사용되는 알고리즘    
- '데이터를 정제' 하는 것
 - '스케일링'.

In [3]:
import pandas as pd             #행렬데이터를 보고 판단하니꽈

#머신러닝에 대한 알고리즘을 갖고 있는 사이킷런
#라이브러리 중 규모가 큰 것들은 이렇게 아래처럼 일부만 가져올 수 있음
from sklearn.datasets import load_iris  #(load_iris: 이거 함수임)

In [4]:
#load_iris(): iris 데이터를 다운로드 받으시오
data = load_iris()


#머신러닝에서 내가 알고 있는 수집 가능한 실제 데이터 값 -> data의 data (data.data)  => x
#머신러닝에서 나의 모델(머신러닝)이 예측하고자 하는 값 -> data.target  => y
print(data.data, '\n')      #꽃잎의 길이, 꽃잎의 넓이,,~ 4가지 항목 (dimensionality = 4)
print(data.target)          #품종

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [5]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
#데이터프레임 변환
X = pd.DataFrame(data.data,columns = data.feature_names)
Y = pd.DataFrame(data.target, columns = ['species'])

In [7]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
#concat([여러 개의 데이터 프레임], axis= 축 옵션)
df = pd.concat([X,Y], axis = 1)
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

# 분류 알고리즘
 - knn(k-최근접 이웃)
 - 의결나무
 - 앙상블(랜덤 포레스트)
 - 로지스틱 회귀(logistic regression)
 - svm(support vector machine)
 - 나이브 베이즈(Naive Bayes)

#KNN 알고리즘

 -K Nearest Neighbor: 유유상종

In [9]:
#사이킷런의 knn 알고리즘(분류)을 import 코드
from sklearn.neighbors import KNeighborsClassifier          #사이킷런의 이웃들에서 KN로된 분류기를 가져오시오

knn = KNeighborsClassifier(n_neighbors = 3)                 #클래스.객체 정의. =  KNN 알고리즘 수행할 것을 생성. (이웃의 수는 3명으로 옵션 지정) 얘는 knn이라 정의
#fit은 knn 모델 안에 학습한 흔적이 남도록 설정되어 있음. 별도로 변수 지정 knn=knn.fit(~)하지 않아도 됨
knn.fit(X,Y)                                                #knn에게 X,Y를 인풋, 이를 기반으로 훈련 지시.(모델.fit(문제,정답지)형태)

#정답 안 보고 학습 내용 토대로 '예측' predict
#knn_predict는 예측 결과. 이 결과가 좋으면 시장에서 배포 가능, 결과 안 좋으면 재훈련
knn_predict = knn.predict(X)                                #knn에 X값을 줄테니 예측치를 도출하시오.  #분석가 입장에선 예측치가 얼마나 잘 맞는지만 판단하면 됨.

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [10]:
print(knn_predict)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [11]:
#얼마나 잘 맞는지? 판단하기

# 정확도 확인 함수
            #.metrics : 평가기준 폴더~
from sklearn.metrics import accuracy_score
accuracy_score(Y,knn_predict)       #(정답,예측)

0.96

머신러닝 좋은 모델 판단기준
 - 많이 맞췄는가? (정확성) 단순하게
 - 의료 음성,양성 (진,가짜) 복합적인 지표

## 2. 의사결정 나무,  랜덤 포레스트 알고리즘


- 성능이 좋음 쥔짜 좋음


-1. 의사결정 나무
- easy to understand
- 1 알고리즘

-2. 랜덤 포레스트 = 앙상블
- 다수의 의사결정 나무 조합

In [12]:
#의결나무

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X,Y)

dt_predict = dt.predict(X)
accuracy_score(Y, dt_predict)

#단점: 보통 1점이 나온다..
#즉, 과적합 문제 or 과소적합. (문제가 너무 많아!) 보통 과적합이 더 나옴

1.0

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score      #성능 평가 안된다? 요놈 추가하삼

#객체 정의                                      #기준
rf = RandomForestClassifier(n_estimators = 50, criterion = 'entropy')           #괄호 내 옵션 삽입 가능, 옵션 검색은 sklearn.ensemble 검색하쇼. n_estimators :나무 몇 그루?(기본 100), max_depth: 나무 가지의 깊이

#훈련
rf.fit(X,Y)

#예측
rf_predict = rf.predict(X)

#성능 평가
accuracy_score(Y,rf_predict)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

1.0

In [18]:
from sklearn.linear_model import LogisticRegression     #
from sklearn.svm import SVC                             #
from sklearn.naive_bayes import GaussianNB              #

In [23]:
import warnings

warnings.filterwarnings('ignore')

In [24]:
from sklearn.linear_model import LogisticRegression

#객체 정의
lr = LogisticRegression()
svc = SVC()
nb = GaussianNB()

#훈련
lr.fit(X,Y)
svc.fit(X,Y)
nb.fit(X,Y)

#예측
lr_predict = lr.predict(X)
svc_predict = svc.predict(X)
nb_predict = nb.predict(X)

#성능 평가
# accuracy_score(Y,lr_predict)
# accuracy_score(Y,svc_predict)
# accuracy_score(Y,nb_predict)


Ir_score = accuracy_score(Y, lr_predict)
svc_score = accuracy_score(Y,svc_predict)
nb_score = accuracy_score(Y,nb_predict)


print(f'Ir의 성능 {Ir_score}, svc 성능 {svc_score}, nb 성능 {nb_score}')

Ir의 성능 0.9733333333333334, svc 성능 0.9733333333333334, nb 성능 0.96