# 인코딩?

- 데이터를 정제(preprocessing)하는 과정에서 수치적인 범위가 너무 넓거나 좁은 데이터들을 정리하고 글자로 된 데이터들을 숫자로 변환하는 것.
-수치적인 범위가 너무 넓거나 좁은 데이터들을 정리하고:


 1. 라벨 인코딩(라벨을 붙임)
 - 순서대로, 범주만.
 - 전세(0), 월세(1), 자가(2)
    - 장점: 간편함
    - 단점: 우열이 없는 데이터를 있다고 보이게 할 수 있음. -> 사칙연산 오해 가능.
    - 즉, 숫자에 크기의 의미를 부여하게 됨.

 2. 원핫인코딩(범주형+
 - 0 원, 1 핫.  데이터의 수만큼 0으로 표시, 해당 자리만 1을 표기함.

    - 전세 001
    - 월세 010
    - 자가 100
    - -> 열이 끊임없이 길어지는 단점 = 차원이 늘어남 (특징이 늘어남)

    - 대신. 변환된 데이터 사이 우열이 없다는 장점.
3. 바이너리 (이진) 인코딩
- 월세 (1) -> 0 1
- 자가 (2) -> 1 0
-  => 라벨 인코딩 + 원 핫 인코딩의 중간 방식.

 - 원핫으로 하면 차원이 지나치게 늘어남. 이런 차원 늘어짐을 방지하고 고유 특성을 지키고 싶을 때.

4. frequency encoding
- 전체 열 중에서 '몇 번이나 나왔냐'를 바탕으로 인코딩

In [ ]:
# 문자열 데이터 인코딩할거야

In [3]:
import pandas as pd

data = {'Color': ['R', 'G', 'B', 'G', 'B']}

df = pd.DataFrame(data)
print(df)

  Color
0     R
1     G
2     B
3     G
4     B

In [11]:
#라벨 인코더, 원핫 인코더 (객체라 모델 쓰듯 사용)

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 객체 생성 -> 열에 대한 정보를 바탕으로 바꿔야하기에
le = LabelEncoder()
oh = OneHotEncoder()
#fit_transform: 라벨 인코더가 갖고 있는 '인코딩' 기능을 내가 적용하고자 하는 열의 apply하는 것.
#le라는 이름을 가진 라벨 인코더가 df를 갖고 인코딩을 합니다
#변수 정의 = 학습 후 숫자로 바꾸삼
color = le.fit_transform(df)

#원래 데이터프레임에 붙이기
view = pd.concat([df,pd.DataFrame(color)], axis = 1)

view.head()

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

  Color  0
0     R  2
1     G  1
2     B  0
3     G  1
4     B  0

In [12]:
#원핫 인코더
#객체 정의. Sparse = 희소하다 (0이 많으면 얻을 수 있는 정보가 없음.그러니까 0을 적게 만들어주삼~ 대충 이런 뜻)
#sparse_output = False : 인코딩시 데이터를 희소하지 않게 해달라
oh = OneHotEncoder(sparse_output = False)

#모양 바꾸기
result = oh.fit_transform(df)

#원래 df에 붙이기
view = pd.concat([view, pd.DataFrame(result)], axis = 1)

view.head()

  Color  0    0    1    2
0     R  2  0.0  0.0  1.0
1     G  1  0.0  1.0  0.0
2     B  0  1.0  0.0  0.0
3     G  1  0.0  1.0  0.0
4     B  0  1.0  0.0  0.0

In [13]:
#바이너리 전 install

!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 1.0 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [17]:
import category_encoders as ce

be = ce.BinaryEncoder()
result_b = be.fit_transform(df)
print(result_b)

#값을 합치면 라벨이 됩니당

   Color_0  Color_1
0        0        1
1        1        0
2        1        1
3        1        0
4        1        1

In [19]:
#프리퀀시
    #빈도를 세준다
fe = ce.CountEncoder()

result_f = fe.fit_transform(df)
print(result_f)

   Color
0      1
1      2
2      2
3      2
4      2